### ISSUE TITLE
Custom JSON model

### ISSUE THREAD

**Issue by TheRealJayjayli** [Specy-wot/Scapix#1]
Hello, I have a question - I have made a custom model [minecraft2x](https://github.com/TheRealJayjayli/minecraft2x) and I would like to know if it would be possible to compile a version of your GUI to work with it. At the moment, I have a model file in the form of t7 and json.

Great GUI btw.

**Comment by Specy** [comment]
I'm using the waifu2x CPP bin which allows only for vgg models , you can try to add your own model by creating a new folder in the `models` folder and then putting your model there, then open the GUI and you should find the new model available directly, it scans for every folder inside of the `models` folder and automatically enables it 

https://github.com/Specy-wot/Scapix/blob/6fdcd4a74906c5bf19928da16cafa6d427174038/electron/electron.js#L44

Let me know if it works, I never tried other models before
