### ISSUE TITLE
Export images to different formats?

### ISSUE THREAD

**Issue by mid-ff-play19** [Specy-wot/Scapix#10]
Export images to different formats, such as png; webp & etc.

**Comment by Specy** [comment]
It's already possible but it's but in the UI is not the clearest, in the app you can rename the file, you can also change the file format and it will convert it. I might add something more clear to understand

**Comment by Specy** [comment]
added in 2f30f6bb0fc0a69efdd7c7345e1f74cc75fa3aac
![image](https://user-images.githubusercontent.com/59029985/235358775-38e03faf-b59a-4f05-aabe-d3529c5332c3.png)

**Comment by mid-ff-play19** [comment]
> added in [2f30f6b](https://github.com/Specy/Scapix/commit/2f30f6bb0fc0a69efdd7c7345e1f74cc75fa3aac) ![image](https://user-images.githubusercontent.com/59029985/235358775-38e03faf-b59a-4f05-aabe-d3529c5332c3.png)

wow, thanks

**Comment by Specy** [comment]
i'll publish it in next update
