### ISSUE TITLE
When working with videos, can intermediate files be lossless compressed?

### ISSUE THREAD

**Issue by S-shangli** [Specy-wot/Scapix#11]
When handling video, an intermediate file is output in JPEG, but I'm worried about the deterioration of the image quality in that intermediate file.
Is it possible to output intermediate files in a lossless format such as PNG?
thankyou.

**Comment by Specy** [comment]
Yes should be doable, I'll make a pull request to the waifu2x module to add it [Here](https://github.com/Tenpi/waifu2x/blob/2f898167c89b469e014eb77dc88fbd6967290ab5/waifu2x.ts#L713).
I'll add this as a static settings

**Comment by Specy** [comment]
i've talked with the lib author and saw that using png would not degrade much quality but would increase the file size of the individual frames by a lot so it is best to keep jpg
