### ISSUE TITLE
Usage a video card

### ISSUE THREAD

**Issue by VicMahoney** [Specy-wot/Scapix#18]
Hello! Question about using the video card - the task manager shows jumping parameters from 2 to 20% of use.Aida shows 79%. Video card rtx 3060 ti. 
Is it possible to load the card at 100 to make the process go faster?

**Comment by Specy** [comment]
That's offloaded to waifu2x or esrgen upscalers, are you upscaling a single file or more than one? If you are doing multiple files you can increase the parallel upscales (settings), if you are doing a single file, it's not on my control to set the usage

**Comment by VicMahoney** [comment]
@Specy single.Understood,thanks
