### ISSUE TITLE
The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library KERNEL32.dll.

### ISSUE THREAD

**Issue by nonam3user** [Specy-wot/Scapix#19]
During installation version 2.1 pop up two message "The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library KERNEL32.dll." and installation aborts. Version 2.0 installs fine.

Windows 7 x64 with no problems

**Comment by Specy** [comment]
Since electron 23, windows 7/8.1 aren't supported anymore, that's why you got that error, in version 2.1 I'm using electron 24

**Comment by Specy** [comment]
https://www.electronjs.org/blog/electron-23-0

You could maybe try to build the app from source by downgrading the electron version manually, I'm not sure if it there are breaking changes I'm using for version 22

You can try by:
1) cloning the repository (you need node.js installed)
2) running the "npm run installDeps"
3) running "npm install electron@22.3.27"
4) running "npm run build"

**Comment by nonam3user** [comment]
Thanks

**Comment by Specy** [comment]
I'm gonna close the issue if you managed to solve the issue, reopen if needed
