### ISSUE TITLE
Upscaling with Transparency

### ISSUE THREAD

**Issue by RABIDYOTE** [Specy-wot/Scapix#2]
I noticed while using Scapix that it has issues with upscaling when an image is transparent. It gives this weird white outline around the image, but the non-transparent parts are fine. I checked and noise reduction, changing the output format, and image type doesn't cause this -- only upscaling. To note, this does not happen on the original demo site for Waifu2x.

Here's an example of what I mean (this isn't the original image I tried to use).

Upscaled:
![Winter-idle](https://user-images.githubusercontent.com/78206431/106263036-d85e3f80-61f1-11eb-8978-d3ef62956273.png)
Original:
![Winter-idle](https://user-images.githubusercontent.com/78206431/106263054-deecb700-61f1-11eb-9cc1-479c7e761cae.png)

**Comment by Specy** [comment]
https://github.com/DeadSix27/waifu2x-converter-cpp/issues/183#issuecomment-620078154
Looks like an issue with waifu2x CPP sadly :/
