### ISSUE TITLE
Just found this, looks awesome overall. Just have 2 improvement ideas. 

### ISSUE THREAD

**Issue by JFMugen** [Specy-wot/Scapix#3]
I will mainly use this for videos, so i had 2 important problems that (I believe) easy to fix. 

* "Max video frames at a time" should be changeable in real time. So I can lower it when I need that computer power and choose how much power I want to use without canceling/restarting again. (actually, fixing the second issue makes this one a lot smaller issue) 

* Instead of turning the video to images again (after a cancel for example) make it reuse already separated images. Just a name-check should be enough, right? 

These two would be very helpful, especially on the longer videos imo. 

Thanks for the app!

**Comment by Specy** [comment]
That part of the code is handled in https://github.com/Tenpi/waifu2x and not by me (it's a module / wrapper for waifu2x) you could try to create an issue there. 

Also just some info, how long videos are you upscaling? What resolution? What GPU do you have? How long does it take to upscale? Have you had issues with audio in upscaled videos? 

Just want to get some info about the program running on different devices.

**Comment by JFMugen** [comment]
I haven't been able to text, just tried with 1 frame at once and it was extremely slow so tried Issue 1 and it didn't work. Then I abort and tried again, but after realizing it separates frames again, I aborted again and created this post. 

I will update this if I can test again tho. 

(By the way, the second issue shouldn't be about waifu2x, am I wrong?)

**Comment by Specy** [comment]
As you can see at 
https://github.com/Specy-wot/Scapix/blob/3b0d12a162beb0fa4b1e29283531c4d47c2f5095/electron/electron.js#L206
I'm using the waifu2x.upscaleVideo() with parallel frames option, it can be set only at first when you call the function, the function which is called comes from a module (waifu2x) which is not mine but from the link I sent you. Also what GPU do you have? If you don't have one then expect video upscale to be REALLY slow. My GPU takes 3 hours to upscale a 1min video to fullhd for example (pretty old one, gtx 960m), with an rtx3080 it takes 30 mins for the same video.

**Comment by JFMugen** [comment]
>gtx 960m

I feel you :/ Its the same. 

And thanks for the answer, I am going to create a post there.
