### ISSUE TITLE
Web

### ISSUE THREAD

**Issue by Kadantte** [Specy-wot/Scapix#4]
How about making Scapix accessible via web browser I mean like [waifu2x](http://waifu2x.udp.jp/)?

**Comment by Specy** [comment]
Oh sorry for the late answer, forgot to reply. Anyway, this program was meant to replace the web version and instead have a offline variant that is easy to use and that doesn't require internet connection. It has no size limits and brings extra functionality. Plus it uses the waifu2x lib which would require an actual server to run.

**Comment by Kadantte** [comment]
Yeah, I like the idea also thanks for making it <3 , I just was looking for a way to run it across all my devices at home from my own Servers a local website! thanks for your reply.

**Comment by Specy** [comment]
The client side code uses react so it should be able to run on the browser too with some changes. If you want to work on it you should be able to change the calls between client and electron and instead make it call a server. Only issue is that both client and electron server make high use of local files so you would have to modify a lot to make it work.

**Comment by Kadantte** [comment]
Thanks now I know what it needs to be done, I'll start on trying what you say.
