### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by zoldaten** [Specy-wot/Scapix#5]
see error when try to open "Output folder".
I converted just 1 image.
Converted image exists in folder but i cant get there with GUI.

**Comment by Specy** [comment]
Could you give more info? What did you try to convert, where the error originated, try to open devtools (should be F12, don't remember how I set it up) and show the error

**Comment by zoldaten** [comment]
i convert 1 photo in jpg format. The coversion finished successful - file exists but i cant reach it with GUI.
When i press in main menu "Open output folder" in right up corner pop-ups message: "Type error..."
screen with error:
https://disk.yandex.ru/i/xrfhnc5zLEPd-g

**Comment by Specy** [comment]
Could you send me a screenshot of the console when you get that error? press CTRL + Shift + i and go to the `console`, send a screenshot of that

**Comment by zoldaten** [comment]
```
Error in main thread:                                                                                                         index.js:35 
TypeError: callback is not a function                                                                                 index.js:36 
    at ChildProcess.<anonymous> (C:\Users\Al\AppData\Local\scapix\app-1.5.0\resources\app\node_modules\open-file-explorer\lib\win.js:13:16)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by Specy** [comment]
i'm not sure how to reproduce this, also the project is not really in development at the moment, i'd have to rewrite it from 0 because the code is pretty bad so i'll keep this open for when i have time for that

**Comment by Specy** [comment]
I rewrote the app, I hope it's not an issue anymore, reopen if it persists
