### ISSUE TITLE
Unable to build on Ubuntu

### ISSUE THREAD

**Issue by CHJ85** [Specy-wot/Scapix#6]
First I git clone'd the repository, then cd'd into the ~/Scapix directory; 
```
❯ npm run deploy-step1

> scapix@1.5.0 deploy-step1
> react-scripts build

sh: 1: react-scripts: not found

```
Am I doing this in the wrong directory or something?

**Comment by Specy** [comment]
Did you install dependencies with `npm i` first? also i never tried to build on linux so i'm not sure if it works, but u can try

**Comment by CHJ85** [comment]
I must have glanced over that. But now I'm stuck at the node_modules/waifu2x/waifu2x thing. Not sure what to do here.
There's no waifu2x file or a node_modules/waifu2x/ directory in the Scapix package.
I think I'll just look for an app that is cross platform instead. Thanks anyway.

**Comment by Specy** [comment]
Ok! When I get to rewrite this I'll make use of a better upscale algorithm too so that it can work closs platform

**Comment by CHJ85** [comment]
Okay thank you.
