### ISSUE TITLE
Randomly not working any more

### ISSUE THREAD

**Issue by GeekyFerret** [Specy-wot/Scapix#7]
I installed this program earlier this year and it worked perfectly. I recently reinstalled it and it no longer upscales any more, all entries immediately turn red when clicking run all.

**Comment by Specy** [comment]
I haven't changed the code since for years so it should have still worked, it might be a problem of File permissions, try to import the image from the desktop and change the output folder to something else

I really should rewrite this app

**Comment by GeekyFerret** [comment]
I found the problem was that msvcp140.dll was missing. Installing the visual c++ redistributable package solved it.

**Comment by Specy** [comment]
Thanks for finding out, it might help others
